version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT:-5000}:5000

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_BACKEND_URL: ${VUE_APP_BACKEND_URL}
        VUE_APP_SERVE_PATH: ${VUE_APP_SERVE_PATH:-/}
    ports:
      - ${FRONTEND_PORT:-3000}:8080
