version: '3.3'

services:
  backend:
    image: dockerogc/ogc-playground-backend
    environment:
      - REMOTE_FETCH_ALLOWED
    ports:
      - ${BACKEND_PORT:-5000}:5000

  frontend:
    image: dockerogc/ogc-playground-frontend
    environment:
      VUE_APP_BACKEND_URL: ${VUE_APP_BACKEND_URL:-http://localhost:5000}
      VUE_APP_SERVE_PATH: ${VUE_APP_SERVE_PATH:-/}
    ports:
      - ${FRONTEND_PORT:-3000}:8080
