version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      args:
        OGC_PLAYGROUND_BACKEND: http://backend:5000
    ports:
      - 3000:3000