version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:5000

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_BACKEND_URL: http://localhost:${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:8080