version: '3.3'

services:
  backend:
    build: ./backend
    image: dockerogc/ogc-playground-backend
    environment:
      - REMOTE_FETCH_ALLOWED
    ports:
      - ${BACKEND_PORT:-5000}:5000

  frontend:
    build: ./frontend
    image: dockerogc/ogc-playground-frontend
    ports:
      - ${FRONTEND_PORT:-3000}:8080
